In [1]:
import numpy as np   # Importo paquete de álgebra lineal
import matplotlib.pyplot as plt   # Importo paquete de gráficos
import math   # Importo paquete de funciones matemáticas
import random   # Importo paquete para generar números pseudoaleatorios

## Problema 4

Encuentre la solución al sistema [A] {x} = {b} correspondiente al siguiente sistema de ecuaciones:
\begin{align*}
    \left\lbrace
    \begin{array}{ccc}
    x - 3y - 2z &=& 6 \\
    2x - 4y - 3z &=& 8 \\
    -3x + 6y + 8z &=& -5 \\
    \end{array}
    \right. \\
\end{align*}

In [2]:
# Defino la matriz de coeficientes "A".
A = np.array([[1,-3,-2],[2,-4,-3],[-3,6,8]])

# Otra manera de hacerlo hubiese sido:
# A = np.array(
#    [
#        [1,-3,-2],
#        [2,-4,-3],
#        [-3,6,8]
#    ]
#)

In [3]:
print(A)

[[ 1 -3 -2]
 [ 2 -4 -3]
 [-3  6  8]]


In [4]:
# Defino el vector de términos independientes "b".
b = np.array([[6],[8],[-5]])

# Otra manera de hacerlo hubiese sido:
# b = np.array(
#    [
#        [6],
#        [8],
#        [-5]
#    ]
#)

In [5]:
print(b)

[[ 6]
 [ 8]
 [-5]]


In [6]:
# Resuelvo el sistema de ecuaciones lineales, obteniendo el vector solución "x".
x = np.linalg.solve(A,b)

In [7]:
print(x)

[[ 1.]
 [-3.]
 [ 2.]]


In [8]:
# Verifico que "x" sea correcto, haciendo el producto entre "A" y "x" y buscando obtener "b".
A.dot(x)

array([[ 6.],
       [ 8.],
       [-5.]])

In [9]:
# Verifico que "x" sea correcto, haciendo el producto entre "A" y "x", restando "b" y buscando obtener [[0],[0],[0]].
A.dot(x)-b

array([[ 1.77635684e-15],
       [-8.88178420e-16],
       [ 0.00000000e+00]])